services:
  db:
    image: postgres:15-alpine
    container_name: assessor-db
    environment:
      POSTGRES_DB: assessor
      POSTGRES_USER: assessor_user
      POSTGRES_PASSWORD: assessor_pass
      TZ: America/Sao_Paulo
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U assessor_user -d assessor']
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: assessor-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@assessor.local
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - db

  ollama:
    image: ollama/ollama:latest
    container_name: assessor-ollama
    ports:
      - '11434:11434'
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_KEEP_ALIVE=24h
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:11434/api/version']
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: assessor-backend
    environment:
      NODE_ENV: development
      PORT: 3001
      DATABASE_URL: postgres://assessor_user:assessor_pass@db:5432/assessor
      TZ: America/Sao_Paulo
      JWT_SECRET: ${JWT_SECRET:-dev-jwt-secret-change-in-production}
      WA_VERIFY_TOKEN: ${WA_VERIFY_TOKEN:-dev-verify-token}
      WA_ACCESS_TOKEN: ${WA_ACCESS_TOKEN:-dev-access-token}
      WA_PHONE_NUMBER_ID: ${WA_PHONE_NUMBER_ID:-dev-phone-id}
      SUPABASE_URL: ${SUPABASE_URL:-https://example.supabase.co}
      SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY:-dev-anon-key}
      SUPABASE_SERVICE_KEY: ${SUPABASE_SERVICE_KEY:-dev-service-key}
      LLM_ENABLED: ${LLM_ENABLED:-true}
      LLM_PROVIDER: ${LLM_PROVIDER:-ollama}
      LLM_BASE_URL: ${LLM_BASE_URL:-http://ollama:11434}
      LLM_MODEL: ${LLM_MODEL:-gemma2:2b}
      LLM_MAX_TOKENS: ${LLM_MAX_TOKENS:-500}
      LLM_TEMPERATURE: ${LLM_TEMPERATURE:-0.1}
    ports:
      - '3001:3001'
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy
      ollama:
        condition: service_started
    command: npm run dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: assessor-frontend
    environment:
      VITE_API_URL: http://localhost:3001
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    command: npm run dev

volumes:
  postgres_data:
  ollama_data:
